### ISSUE TITLE
3.1.x - won't build if pcap.h is not available

### ISSUE THREAD

**Issue by nchaigne** [FreeRADIUS/freeradius-server#1150]
FreeRADIUS doesn't build anymore if we don't have pcap.h, since the following commit:

https://github.com/FreeRADIUS/freeradius-server/commit/c56112bb0e72b2330b2c8882ba7266453d6ab9f6

	In file included from /home/admwpdhcp/src-dhcpbench/freeradius-server-3.1.x-dhb-c1/src/lib/dict.c:27:0:
	/home/admwpdhcp/src-dhcpbench/freeradius-server-3.1.x-dhb-c1/src/freeradius-devel/dhcp.h:30:18: fatal error: pcap.h: No such file or directory
	 #include <pcap.h>

**Comment by nchaigne** [comment]
The whole patch is wrong I think, it should use #ifdef HAVE_LIBPCAP

**Comment by alandekok** [comment]
Fixed by commit 57bc79f

**Comment by nchaigne** [comment]
It still doesn't build, you've missed some:

	CC /home/admwpdhcp/src-dhcpbench/freeradius-server-3.1.x-dhb-c1/src/modules/rlm_always/rlm_always.c
	In file included from /home/admwpdhcp/src-dhcpbench/freeradius-server-3.1.x-dhb-c1/src/freeradius-devel/process.h:30:0,
					 from /home/admwpdhcp/src-dhcpbench/freeradius-server-3.1.x-dhb-c1/src/freeradius-devel/radiusd.h:66,
					 from /home/admwpdhcp/src-dhcpbench/freeradius-server-3.1.x-dhb-c1/src/modules/rlm_always/rlm_always.c:27:
	/home/admwpdhcp/src-dhcpbench/freeradius-server-3.1.x-dhb-c1/src/freeradius-devel/listen.h:116:2: error: unknown type name ‘fr_pcap_t’
	  fr_pcap_t *pcap;
	  ^
	/home/admwpdhcp/src-dhcpbench/freeradius-server-3.1.x-dhb-c1/src/freeradius-devel/listen.h:117:2: error: unknown type name ‘fr_pcap_type_t’
	  fr_pcap_type_t pcap_type;
	  ^

**Comment by nchaigne** [comment]
And more issues after fixing listen.h:

	CC /home/admwpdhcp/src-dhcpbench/freeradius-server-3.1.x-dhb-c1/src/modules/proto_dhcp/dhcpclient.c
	/home/admwpdhcp/src-dhcpbench/freeradius-server-3.1.x-dhb-c1/src/modules/proto_dhcp/dhcpclient.c:57:8: error: unknown type name ‘fr_pcap_t’
	 static fr_pcap_t *pcap;
			^
	/home/admwpdhcp/src-dhcpbench/freeradius-server-3.1.x-dhb-c1/src/modules/proto_dhcp/dhcpclient.c: In function ‘fr_dhcp_recv_raw_loop’:
	/home/admwpdhcp/src-dhcpbench/freeradius-server-3.1.x-dhb-c1/src/modules/proto_dhcp/dhcpclient.c:360:4: warning: implicit declaration of function ‘fr_dhcp_recv_pcap’ [-Wimplicit-function-declaration]
		cur_reply_p = fr_dhcp_recv_pcap(pcap);
		^
