### ISSUE TITLE
Possible segfault/assertion error on else without if

### ISSUE THREAD

**Issue by qnet-herwin** [FreeRADIUS/freeradius-server#1355]
In the default config, change the value of authorize in default virtual server to this:

```
authorize {
  else {
  }
}
```

In 3.0.x, I sometimes get a segfault here, but sometimes an assertion error is hit. This happens around lines 2826-2833 in `modcall.c`, exactly above the point that should error on the missing if.

In my current gdb session, the value of `p->tail` is `0x3c`, which isn't what you'd normally expect a pointer to be.

**Comment by alandekok** [comment]
Check the git head. This was already fixed in 3.0.10

**Comment by jpereira** [comment]
@alandekok Still broken

```
Tue Oct 27 13:37:51 2015 : Error: ASSERT FAILED src/main/modcall.c[2866]: p->tail != NULL
CAUGHT SIGNAL: Aborted
Backtrace of last 12 frames:
/opt/radius/lib/libfreeradius-radius.so(fr_fault+0x12d)[0x7febc813297a]
/opt/radius/lib/libfreeradius-server.so(rad_assert_fail+0x46)[0x7febc839812d]
/opt/radius/sbin/radiusd[0x42f839]
/opt/radius/sbin/radiusd[0x42e69d]
/opt/radius/sbin/radiusd(compile_modsingle+0x15c)[0x42f341]
/opt/radius/sbin/radiusd[0x4282bf]
/opt/radius/sbin/radiusd[0x42874a]
/opt/radius/sbin/radiusd(virtual_servers_load+0x1a7)[0x428cc8]
/opt/radius/sbin/radiusd(modules_init+0x992)[0x429fb8]
/opt/radius/sbin/radiusd(main+0x94e)[0x432f19]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7febc6ecea40]
/opt/radius/sbin/radiusd(_start+0x29)[0x40e8b9]

``

**Comment by jpereira** [comment]
@alandekok and @qnet-herwin This patch https://github.com/FreeRADIUS/freeradius-server/pull/1356 works well!

```
Tue Oct 27 13:47:07 2015 : Error: /opt/radius/etc/raddb/sites-enabled/default[258]: Invalid location for 'else'. There is no preceding 'if' statement
Tue Oct 27 13:47:07 2015 : Error: /opt/radius/etc/raddb/sites-enabled/default[254]: Errors parsing authorize section. 
```
