### ISSUE TITLE
Segmentation fault when rlm_python generates too much RADIUS Attribute Tuples

### ISSUE THREAD

**Issue by alejandro-perez** [FreeRADIUS/freeradius-server#1535]
If I make my python module to generate enough tuples to exceed the 4KB limit, FR (3.1.0) sigsegvs. I'm not sure whether this is particular to rlm_python or it is something that might happen with any other module.

Here you are a backtrace.
```
#0  0x00007ffff6ed0691 in talloc_chunk_from_ptr () from /usr/local/lib/libtalloc.so.2
#1  0x00007ffff6ed2266 in __talloc_get_name () from /usr/local/lib/libtalloc.so.2
#2  0x00007ffff6ed2400 in _talloc_get_type_abort () from /usr/local/lib/libtalloc.so.2
#3  0x00007ffff795dd31 in fr_pair_verify (file=0x7ffff7977570 "src/lib/cursor.c", line=306, 
    vp=0x640000061ae38a30) at src/lib/pair.c:2513
#4  0x00007ffff7949c81 in fr_cursor_current (cursor=0x7fffffffe580) at src/lib/cursor.c:306
#5  0x00007ffff7963756 in encode_value (out=0x7fffffffe5a3 "", outlen=249, 
    tlv_stack=0x7fffffffd420, depth=2, cursor=0x7fffffffe580, encoder_ctx=0x7fffffffe560)
    at src/lib/radius_encode.c:609
#6  0x00007ffff7964d0c in encode_rfc_hdr_internal (out=0x7fffffffe5a1 "\212\002", outlen=249, 
    tlv_stack=0x7fffffffd420, depth=2, cursor=0x7fffffffe580, encoder_ctx=0x7fffffffe560)
    at src/lib/radius_encode.c:1107
#7  0x00007ffff7964ef7 in encode_vendor_attr_hdr (out=0x7fffffffe5a1 "\212\002", outlen=249, 
    tlv_stack=0x7fffffffd420, depth=2, cursor=0x7fffffffe580, encoder_ctx=0x7fffffffe560)
    at src/lib/radius_encode.c:1147
#8  0x00007ffff7965b9a in encode_vsa_hdr (out=0x7fffffffe59b "\032\006", outlen=249, 
    tlv_stack=0x7fffffffd420, depth=1, cursor=0x7fffffffe580, encoder_ctx=0x7fffffffe560)
    at src/lib/radius_encode.c:1397
#9  0x00007ffff79663e1 in fr_radius_encode_pair (out=0x7fffffffe59b "\032\006", 
    outlen=18446744073709551557, cursor=0x7fffffffe580, encoder_ctx=0x7fffffffe560)
    at src/lib/radius_encode.c:1577
#10 0x00007ffff7961816 in fr_radius_encode (packet=0xe15b70, original=0xe157d0, 
    secret=0x98a110 "saml-aaa") at src/lib/radius.c:1451
#11 0x00007ffff7960326 in fr_radius_send (packet=0xe15b70, original=0xe157d0, 
    secret=0x98a110 "saml-aaa") at src/lib/radius.c:548
#12 0x0000000000419d7a in auth_socket_send (listener=0x98c670, request=0xe159a0)
    at src/main/listen.c:1650
#13 0x0000000000439df7 in request_finish (request=0xe159a0, action=1) at src/main/process.c:1418
#14 0x000000000043a103 in request_running (request=0xe159a0, action=1)
    at src/main/process.c:1514
#15 0x0000000000438d90 in request_queue_or_run (request=0xe159a0, 
    process=0x439f28 <request_running>) at src/main/process.c:956
#16 0x000000000043a98b in request_receive (ctx=0xe15770, listener=0x98c670, packet=0xe157d0, 
    client=0x989850, fun=0x410e92 <rad_authenticate>) at src/main/process.c:1740
#17 0x000000000041a84e in auth_socket_recv (listener=0x98c670) at src/main/listen.c:1898
#18 0x00000000004416c2 in event_socket_handler (xel=0xe07010, fd=14, ctx=0x98c670)
    at src/main/process.c:4525
#19 0x00007ffff79759ab in fr_event_loop (el=0xe07010) at src/lib/event.c:637
#20 0x000000000044343a in radius_event_process () at src/main/process.c:5574
#21 0x0000000000431c4d in main (argc=2, argv=0x7fffffffec68) at src/main/radiusd.c:586
```

**Comment by alandekok** [comment]
Can you try git HEAD?  I pushed some fixes which I think should help.

**Comment by alejandro-perez** [comment]
Umm, still having problems (does not seem to be **exactly** the same). In case it helps, I'm sending a SAML-Assertion UKERNA vendor specific attribute. The contents you see in #6 do not look like what I sent (some errors in the string, such as paml instead of saml. I guess memory is getting corrupted.
```
#1  0x00007ffff6ed1266 in __talloc_get_name () from /usr/local/lib/libtalloc.so.2
#2  0x00007ffff6ed1400 in _talloc_get_type_abort () from /usr/local/lib/libtalloc.so.2
#3  0x00007ffff795cf49 in fr_pair_verify (file=0x7ffff79767d0 "src/lib/cursor.c", line=269, vp=0x727474413a6c6d61) at src/lib/pair.c:2522
#4  0x00007ffff7948cb0 in fr_cursor_next (cursor=0x7fffffffe560) at src/lib/cursor.c:269
#5  0x00007ffff7963087 in encode_value (out=0x7fffffffe54e "saml:AttributeValue><saml:AttributeValue>paml:Attraml:AttributeValue><saml:AttributeValue>organizationalPerson</saml:Att", outlen=247, 
    tlv_stack=0x7fffffffd400, depth=2, cursor=0x7fffffffe560, encoder_ctx=0x7fffffffe540) at src/lib/radius_encode.c:825
#6  0x00007ffff7963f0d in encode_rfc_hdr_internal (
    out=0x7fffffffe54c "\204\002saml:AttributeValue><saml:AttributeValue>paml:Attraml:AttributeValue><saml:AttributeValue>organizationalPerson</saml:Att", outlen=249, tlv_stack=0x7fffffffd400, 
    depth=2, cursor=0x7fffffffe560, encoder_ctx=0x7fffffffe540) at src/lib/radius_encode.c:1104
#7  0x00007ffff79640f8 in encode_vendor_attr_hdr (
    out=0x7fffffffe54c "\204\002saml:AttributeValue><saml:AttributeValue>paml:Attraml:AttributeValue><saml:AttributeValue>organizationalPerson</saml:Att", outlen=249, tlv_stack=0x7fffffffd400, 
    depth=2, cursor=0x7fffffffe560, encoder_ctx=0x7fffffffe540) at src/lib/radius_encode.c:1144
#8  0x00007ffff7964dbf in encode_vsa_hdr (out=0x7fffffffe546 "\032\006", outlen=249, tlv_stack=0x7fffffffd400, depth=1, cursor=0x7fffffffe560, encoder_ctx=0x7fffffffe540)
    at src/lib/radius_encode.c:1392
#9  0x00007ffff7965624 in fr_radius_encode_pair (out=0x7fffffffe546 "\032\006", outlen=18446744073709551610, cursor=0x7fffffffe560, encoder_ctx=0x7fffffffe540) at src/lib/radius_encode.c:1576
#10 0x00007ffff7960a2e in fr_radius_encode (packet=0xe22250, original=0xe21eb0, secret=0x98a390 "saml-aaa") at src/lib/radius.c:1451
#11 0x00007ffff795f53e in fr_radius_send (packet=0xe22250, original=0xe21eb0, secret=0x98a390 "saml-aaa") at src/lib/radius.c:548
#12 0x0000000000419c9d in auth_socket_send (listener=0x98c8f0, request=0xe22080) at src/main/listen.c:1648
#13 0x0000000000439f20 in request_finish (request=0xe22080, action=1) at src/main/process.c:1394
#14 0x000000000043a22c in request_running (request=0xe22080, action=1) at src/main/process.c:1490
#15 0x0000000000438ea4 in request_queue_or_run (request=0xe22080, process=0x43a051 <request_running>) at src/main/process.c:925
#16 0x000000000043aab4 in request_receive (ctx=0xe21e50, listener=0x98c8f0, packet=0xe21eb0, client=0x989ad0, fun=0x410e02 <rad_authenticate>) at src/main/process.c:1716
#17 0x000000000041a771 in auth_socket_recv (listener=0x98c8f0) at src/main/listen.c:1896
#18 0x00000000004417eb in event_socket_handler (xel=0xe12aa0, fd=13, ctx=0x98c8f0) at src/main/process.c:4495
#19 0x00007ffff7974bef in fr_event_loop (el=0xe12aa0) at src/lib/event.c:637
#20 0x000000000044357d in radius_event_process () at src/main/process.c:5502
#21 0x0000000000431f5e in main (argc=2, argv=0x7fffffffec48) at src/main/radiusd.c:583
```

**Comment by alandekok** [comment]
If it's a talloc error, my guess is that the rlm_python code is creating incorrect VALUE_PAIRs.

The `VERIFY_VP()` macro exists to check for these things.  I'd suggest adding it to the rlm_python code, to check all VPs it's created.  If it fails there, you know that the rlm_python code is wrong.

If it passes, then something else in the server is breaking the VPs.

Have you tried adding those VPs from the `users` file, or `unlang` directly, instead of via python?  If it works when they're added outside of python, that's another indication that the problem is rlm_python.

**Comment by alejandro-perez** [comment]
I just tried with unlang, and it fails in the same way. Maybe I'm doing something wrong.
Steps to reproduce:
Edit sites-enabled/default and add the following to the end of post-auth section:
```
	update reply {
                        SAML-AAA-Assertion += '<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" IssueInstant="2011-03-19T08:30:00Z" ID="foo" Version="2.0">'
            SAML-AAA-Assertion += '<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" IssueInstant="2011-03-19T08:30:00Z" ID="foo" Version="2.0">'
            SAML-AAA-Assertion += '<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" IssueInstant="2011-03-19T08:30:00Z" ID="foo" Version="2.0">'
            SAML-AAA-Assertion += '<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" IssueInstant="2011-03-19T08:30:00Z" ID="foo" Version="2.0">'
            SAML-AAA-Assertion += '<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" IssueInstant="2011-03-19T08:30:00Z" ID="foo" Version="2.0">'
            SAML-AAA-Assertion += '<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" IssueInstant="2011-03-19T08:30:00Z" ID="foo" Version="2.0">'
            SAML-AAA-Assertion += '<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" IssueInstant="2011-03-19T08:30:00Z" ID="foo" Version="2.0">'
            SAML-AAA-Assertion += '<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" IssueInstant="2011-03-19T08:30:00Z" ID="foo" Version="2.0">'
            SAML-AAA-Assertion += '<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" IssueInstant="2011-03-19T08:30:00Z" ID="foo" Version="2.0">'
            SAML-AAA-Assertion += '<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" IssueInstant="2011-03-19T08:30:00Z" ID="foo" Version="2.0">'
            SAML-AAA-Assertion += '<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" IssueInstant="2011-03-19T08:30:00Z" ID="foo" Version="2.0">'
            SAML-AAA-Assertion += '<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" IssueInstant="2011-03-19T08:30:00Z" ID="foo" Version="2.0">'
            SAML-AAA-Assertion += '<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" IssueInstant="2011-03-19T08:30:00Z" ID="foo" Version="2.0">'
            SAML-AAA-Assertion += '<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" IssueInstant="2011-03-19T08:30:00Z" ID="foo" Version="2.0">'
            SAML-AAA-Assertion += '<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" IssueInstant="2011-03-19T08:30:00Z" ID="foo" Version="2.0">'
            SAML-AAA-Assertion += '<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" IssueInstant="2011-03-19T08:30:00Z" ID="foo" Version="2.0">'
            SAML-AAA-Assertion += '<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" IssueInstant="2011-03-19T08:30:00Z" ID="foo" Version="2.0">'
            SAML-AAA-Assertion += '<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" IssueInstant="2011-03-19T08:30:00Z" ID="foo" Version="2.0">'
            SAML-AAA-Assertion += '<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" IssueInstant="2011-03-19T08:30:00Z" ID="foo" Version="2.0">'
            SAML-AAA-Assertion += '<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" IssueInstant="2011-03-19T08:30:00Z" ID="foo" Version="2.0">'
            SAML-AAA-Assertion += '<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" IssueInstant="2011-03-19T08:30:00Z" ID="foo" Version="2.0">'
            SAML-AAA-Assertion += '<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" IssueInstant="2011-03-19T08:30:00Z" ID="foo" Version="2.0">'
            SAML-AAA-Assertion += '<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" IssueInstant="2011-03-19T08:30:00Z" ID="foo" Version="2.0">'
            SAML-AAA-Assertion += '<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" IssueInstant="2011-03-19T08:30:00Z" ID="foo" Version="2.0">'
            SAML-AAA-Assertion += '<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" IssueInstant="2011-03-19T08:30:00Z" ID="foo" Version="2.0">'
            SAML-AAA-Assertion += '<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" IssueInstant="2011-03-19T08:30:00Z" ID="foo" Version="2.0">'
            SAML-AAA-Assertion += '<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" IssueInstant="2011-03-19T08:30:00Z" ID="foo" Version="2.0">'
            SAML-AAA-Assertion += '<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" IssueInstant="2011-03-19T08:30:00Z" ID="foo" Version="2.0">'
            SAML-AAA-Assertion += '<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" IssueInstant="2011-03-19T08:30:00Z" ID="foo" Version="2.0">'
            SAML-AAA-Assertion += '<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" IssueInstant="2011-03-19T08:30:00Z" ID="foo" Version="2.0">'
            SAML-AAA-Assertion += '<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" IssueInstant="2011-03-19T08:30:00Z" ID="foo" Version="2.0">'
            SAML-AAA-Assertion += '<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" IssueInstant="2011-03-19T08:30:00Z" ID="foo" Version="2.0">'
            SAML-AAA-Assertion += '<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" IssueInstant="2011-03-19T08:30:00Z" ID="foo" Version="2.0">'
            SAML-AAA-Assertion += '<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" IssueInstant="2011-03-19T08:30:00Z" ID="foo" Version="2.0">'
            SAML-AAA-Assertion += '<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" IssueInstant="2011-03-19T08:30:00Z" ID="foo" Version="2.0">'
            SAML-AAA-Assertion += '<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" IssueInstant="2011-03-19T08:30:00Z" ID="foo" Version="2.0">'
            SAML-AAA-Assertion += '<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" IssueInstant="2011-03-19T08:30:00Z" ID="foo" Version="2.0">'
            SAML-AAA-Assertion += '<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" IssueInstant="2011-03-19T08:30:00Z" ID="foo" Version="2.0">'
            SAML-AAA-Assertion += '<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" IssueInstant="2011-03-19T08:30:00Z" ID="foo" Version="2.0">'
            SAML-AAA-Assertion += '<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" IssueInstant="2011-03-19T08:30:00Z" ID="foo" Version="2.0">'
            SAML-AAA-Assertion += '<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" IssueInstant="2011-03-19T08:30:00Z" ID="foo" Version="2.0">'
            SAML-AAA-Assertion += '<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" IssueInstant="2011-03-19T08:30:00Z" ID="foo" Version="2.0">'
            SAML-AAA-Assertion += '<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" IssueInstant="2011-03-19T08:30:00Z" ID="foo" Version="2.0">'
            SAML-AAA-Assertion += '<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" IssueInstant="2011-03-19T08:30:00Z" ID="foo" Version="2.0">'
            SAML-AAA-Assertion += '<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" IssueInstant="2011-03-19T08:30:00Z" ID="foo" Version="2.0">'
            SAML-AAA-Assertion += '<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" IssueInstant="2011-03-19T08:30:00Z" ID="foo" Version="2.0">'
		SAML-AAA-Assertion += '<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" IssueInstant="2011-03-19T08:30:00Z" ID="foo" Version="2.0">'
            SAML-AAA-Assertion += '<saml:Issuer>urn:mace:incommon:osu.edu</saml:Issuer>'
            SAML-AAA-Assertion += '<saml:AttributeStatement>'
            SAML-AAA-Assertion += '<saml:Attribute NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri" Name="urn:oid:1.3.6.1.4.1.5923.1.1.1.7"><saml:AttributeValue>moonshot</saml:AttributeValue></saml:Attribute>'
            SAML-AAA-Assertion += '</saml:AttributeStatement>'
            SAML-AAA-Assertion += '</saml:Assertion>'
```

**Comment by alejandro-perez** [comment]
I closed unintentionally. It is still opened

**Comment by alandekok** [comment]
OK, I can reproduce it here in 3.0 and 3.1 with that configuration.  I'll work on a fix.

**Comment by alandekok** [comment]
OK, I've pushed fixes to both branches.

**Comment by alejandro-perez** [comment]
Great, thanks. It does not sigsegvs now, but the server does not give a clue that attributes were not sent, does it?

**Comment by alandekok** [comment]
No.  The extra attributes are silently truncated.

**Comment by alejandro-perez** [comment]
Is it woth a WARNING? :) Just asking.
