### ISSUE TITLE
[defect]: mongo queries.conf[217]: Parse error: Unterminated string

### ISSUE THREAD

**Issue by craftycram** [FreeRADIUS/freeradius-server#5301]
### What type of defect/bug is this?

Unexpected behaviour (obvious or verified by project member)

### How can the issue be reproduced?

- enable the sql mod
- set dialect to `mongo`
- set driver to `rlm_sql_mongo`
- set server to mongo connect url

### Log output from the FreeRADIUS daemon

```shell
2024-03-04T15:04:03.956296656Z FreeRADIUS Version 3.2.3
2024-03-04T15:04:03.956322337Z Copyright (C) 1999-2022 The FreeRADIUS server project and contributors
2024-03-04T15:04:03.956326087Z There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
2024-03-04T15:04:03.956335117Z PARTICULAR PURPOSE
2024-03-04T15:04:03.956338047Z You may redistribute copies of FreeRADIUS under the terms of the
2024-03-04T15:04:03.956340997Z GNU General Public License
2024-03-04T15:04:03.956343777Z For more information about these matters, see the file named COPYRIGHT
2024-03-04T15:04:03.957026656Z Starting - reading configuration files ...
2024-03-04T15:04:03.957035016Z including dictionary file /usr/share/freeradius/dictionary
2024-03-04T15:04:03.967323698Z including dictionary file /usr/share/freeradius/dictionary.dhcp
2024-03-04T15:04:03.967353008Z including dictionary file /usr/share/freeradius/dictionary.vqp
2024-03-04T15:04:03.967365959Z including dictionary file /etc/freeradius/dictionary
2024-03-04T15:04:03.967386259Z including configuration file /etc/freeradius/radiusd.conf
2024-03-04T15:04:03.967456930Z including configuration file /etc/freeradius/proxy.conf
2024-03-04T15:04:03.967523311Z including configuration file /etc/freeradius/clients.conf
2024-03-04T15:04:03.967565811Z including files in directory /etc/freeradius/mods-enabled/
2024-03-04T15:04:03.967590742Z including configuration file /etc/freeradius/mods-enabled/detail
2024-03-04T15:04:03.967613202Z including configuration file /etc/freeradius/mods-enabled/eap
2024-03-04T15:04:03.967703953Z including configuration file /etc/freeradius/mods-enabled/realm
2024-03-04T15:04:03.967730633Z including configuration file /etc/freeradius/mods-enabled/totp
2024-03-04T15:04:03.967742413Z including configuration file /etc/freeradius/mods-enabled/digest
2024-03-04T15:04:03.967755944Z including configuration file /etc/freeradius/mods-enabled/ntlm_auth
2024-03-04T15:04:03.967766644Z including configuration file /etc/freeradius/mods-enabled/replicate
2024-03-04T15:04:03.967781014Z including configuration file /etc/freeradius/mods-enabled/echo
2024-03-04T15:04:03.967797724Z including configuration file /etc/freeradius/mods-enabled/detail.log
2024-03-04T15:04:03.967822415Z including configuration file /etc/freeradius/mods-enabled/attr_filter
2024-03-04T15:04:03.967847955Z including configuration file /etc/freeradius/mods-enabled/always
2024-03-04T15:04:03.967873735Z including configuration file /etc/freeradius/mods-enabled/utf8
2024-03-04T15:04:03.967884415Z including configuration file /etc/freeradius/mods-enabled/exec
2024-03-04T15:04:03.967899936Z including configuration file /etc/freeradius/mods-enabled/expr
2024-03-04T15:04:03.967917606Z including configuration file /etc/freeradius/mods-enabled/expiration
2024-03-04T15:04:03.967929606Z including configuration file /etc/freeradius/mods-enabled/date
2024-03-04T15:04:03.967941636Z including configuration file /etc/freeradius/mods-enabled/dynamic_clients
2024-03-04T15:04:03.967955496Z including configuration file /etc/freeradius/mods-enabled/preprocess
2024-03-04T15:04:03.967972506Z including configuration file /etc/freeradius/mods-enabled/radutmp
2024-03-04T15:04:03.968006577Z including configuration file /etc/freeradius/mods-enabled/sradutmp
2024-03-04T15:04:03.968013247Z including configuration file /etc/freeradius/mods-enabled/mschap
2024-03-04T15:04:03.968040937Z including configuration file /etc/freeradius/mods-enabled/sql
2024-03-04T15:04:03.968104308Z including configuration file /etc/freeradius/mods-config/sql/main/mongo/queries.conf
2024-03-04T15:04:03.968147919Z /etc/freeradius/mods-config/sql/main/mongo/queries.conf[217]: Parse error: Unterminated string
2024-03-04T15:04:03.968154689Z Errors reading or parsing /etc/freeradius/radiusd.conf
```

**Comment by alandekok** [comment]
Already fixed in 8221f708aaf8

**Comment by craftycram** [comment]
any docker release planned soon? seems like the newest release is older than the fix

**Comment by craftycram** [comment]
update @alandekok:
just replaced the queries.conf with the one from your linked fix. still getting the same error.

**Comment by alandekok** [comment]
If it gets exactly the same error, then I suspect that you didn't update the correct file.  The new version has fixed the issue you're seeing.

What is on line 217 of the file?  i.e. when the error message says:

```
024-03-04T15:04:03.968147919Z /etc/freeradius/mods-config/sql/main/mongo/queries.conf[217]: Parse error: Unterminated string
```

What is the contents of the file at that line?

**Comment by craftycram** [comment]
217 interestingly is just a closing brace.

<img width="1146" alt="grafik" src="https://github.com/FreeRADIUS/freeradius-server/assets/32396733/ae74407c-35ba-4c3c-8150-10113e96980c">

I validated that it's using the new version I got from [here](https://github.com/FreeRADIUS/freeradius-server/blob/8221f708aaf83b8099e873a15bdbc12d242aa17e/raddb/mods-config/sql/main/mongo/queries.conf)

**Comment by alandekok** [comment]
The mongo drivers are not built by default.  You'll have to do that from source, unfortunately.

**Comment by craftycram** [comment]
alright thanks

**Comment by craftycram** [comment]
could you maybe give me another hint on how to setup users with mongo?

<img width="428" alt="grafik" src="https://github.com/FreeRADIUS/freeradius-server/assets/32396733/41bea6ec-44a2-4db3-93eb-7cd462f70c73">

i tried like this, but none of my tries did work

**Comment by alandekok** [comment]
The first object should work.  The second one definitely won't.

To be honest, this functionality is largely experimental, which is why it isn't in the default packages.  If it works, great.  If not, please help by contributing fixes, documentation, etc.

**Comment by craftycram** [comment]
alright thanks that what i was thinking. then i'll just stick with postgress probably.  
thanks for the help
